### ISSUE TITLE
Questions about evaluating derivatives

### ISSUE THREAD

**Issue by swordigo1995** [BachiLi/redner#54]
Hi, Thanks for your awesome work!

I'm new to automatic differentiation and have some trouble in evaluating derivatives.
I see in your paper "we use an operator overloading approach for automatic differentiation", but in this version you imporve it with hand derivatives.

So, what's the problem with original automatic differentiation approach in the paper? Is there some reference materials about how to do it concretely? 
Is there an existing tool which can transform renderer's c++ code to a differentiable c++ implementation directly (if we don't consider visibility problem talked in your paper) ?
I saw "Source-to-source automatic differentiation" in your project's wish list, what's the advantage of this approach compare to current hand derivatives and previous automatic differentiation approach ?

Looking forward to your reply! Thanks a lot!

**Comment by BachiLi** [comment]
Good question. The code we did for the submission built a tape during runtime that records the computational graph and backprop once the forward computation is done. It is based on my autodiff library https://github.com/BachiLi/had but I modified it to only compute the gradients. This approach is convenient and works on any C++ code, and is extensible through templates, but the downside is that the derivatives code/tapes are computed at runtime, and that causes modern compiler failing to optimize the code by properly propagating constants and eliminate unnecessary memory allocation. The fact that it requires dynamic memory allocation (you don't know the tape size before you actually build it) also makes it less friendly to GPUs. My [thesis](https://people.csail.mit.edu/tzumao/phdthesis/phdthesis.pdf) also has some background on this in Chapter 2.

If we have a compiler that computes the derivatives at compile time -- that is, if we take C++ code as input and output the derivatives as C++ (or llvm or ptx), then it would be much more efficient, mostly because we can fold all the constants (common subexpression elimination also helps). I took this approach back in 2015, see this codebase https://github.com/BachiLi/dpt for reference (the codegen part is in chad.h/chad.cpp). The 2015 differentiable renderer builds a symbolic renderer through operator overloading, and more importantly emits C/ispc code at *compile time*. This allows the compiler to optimize the code much better. Unfortunately it was not trivial to scale that approach to differentiate with arbitrary scene parameters and arbitrary path length (it is possible though). I do have plans to write an ispc-like derivative vector compiler, but it might takes some time before I actually adopt it in this renderer. Another paper to look at is our paper on differentiating Halide https://people.csail.mit.edu/tzumao/gradient_halide/. I think the ideal solution is to build a DSL for rendering and take differentiation into account from the beginning of the design.

**Comment by swordigo1995** [comment]
Thanks for your quick response and very clear and useful answer ! 
one small question: The DSL means Differentiable Shading Language?

**Comment by BachiLi** [comment]
Domain Specific Language : )

**Comment by swordigo1995** [comment]
OK, got it!

**Comment by BachiLi** [comment]
Closing since the question is resolved.
