### ISSUE TITLE
Rendering with interpolated vertex colors instead of texture?

### ISSUE THREAD

**Issue by francoisruty** [BachiLi/redner#63]
hi, is it possible to render with redner a mesh with vertex colors, instead of using a texture?

**Comment by BachiLi** [comment]
As mentioned in https://github.com/BachiLi/redner/issues/12, no. But since there is more than one request I might add it in the future. I still think that vertex color is not the "right thing" to do since
1) It is difficult to do proper texture filtering on vertex space.
2) It does not make much sense to use the same sampling rate for both geometry and material.

I think the proper way of doing this is to use a texture (especially now we have automatic uv generation wrapper code thanks to xatlas) and play with the texture resolution. It also plays better with all the convolutional neural network stuffs.

**Comment by francoisruty** [comment]
ok, I'll find a workaround, thanks for the info
(NOTE: I agree using vertex colors is not good but some 3D models that have been dimensionnally reduced by PCA use vertex colors for color information, as it's easier to manipulate with PCA, so in this case the choice is not up to me unfortunately)

**Comment by BachiLi** [comment]
Good point. I will add vertex color sometimes this week.

**Comment by francoisruty** [comment]
that would be awesome, let me know if you need any help, I'd be glad to give you a hand

**Comment by BachiLi** [comment]
Done. See `test_vertex_color.py`. I added a color field to the Shape data structure and a `use_vertex_color` flag in the material so that one can use the color field.

Here's an example fitting grey color to a uniformly random vertex color field.
rendering:
![out](https://user-images.githubusercontent.com/951021/67154884-072ffb00-f2b8-11e9-9abe-0035f6b9a98c.gif)
vertex color visualization:
![out_color](https://user-images.githubusercontent.com/951021/67154888-0e570900-f2b8-11e9-876f-43c03bb3d2c3.gif)

**Comment by francoisruty** [comment]
thanks very much, I'll test this
