### ISSUE TITLE
Question regarding cam._cam_to_ndc in pyredner/camera.py

### ISSUE THREAD

**Issue by francoisruty** [BachiLi/redner#66]
So according to the name of this variable in pyredner/camera.py, multiplying a 3D vector in camera space by this matrix should yield a point in NDC space

However, when I do so, it seems that I need to multiply the vector by _cam_to_ndc, AND THEN divide the result by z coordinate, and only then I'm in NDC
For example:
x,y,z = camera._cam_to_ndc.dot(vector)
x/z and y/z are in NDC (so x and y are not)

is that normal?

I have the impression that your _cam_to_ndc is a kind of variant of OpenCV camera matrix (https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html), except that [ multiply by opencv camera matrix and then divide by z] ends up in screen space, while [ multiply by redner _cam_to_ndc and then divide by z] ends up in NDC

it's not really an issue, I just want to hear the story behind this matrix :)

**Comment by francoisruty** [comment]
The reason I'm asking is that I'm testing stuff with opengl, and I need to replicate in opengl the projection done by redner
I already wrote a whole article about how to match opencv camera matrix with an opengl projection matrix (https://fruty.io/2019/08/29/augmented-reality-with-opencv-and-opengl-the-tricky-projection-matrix/)
and now I have to wrap my head around redner _cam_to_ndc so that I can achieve the exact same projection in opengl

Currently my opengl projection matrix is this:

w = 256
h = 256
near = 0.01
far = 300.0
fovy = 45.0/360.0*2.0*np.pi #45° in radians
f = h / 2*math.tan(fovy/2) #cf http://paulbourke.net/miscellaneous/lens/  (NOTE: focal length is in pixels)
cx = int(w/2.0)
cy = int(h/2.0)
projection_matrix = np.array([
[2*f/w, 0.0, (w - 2*cx)/w, 0.0],
[0.0, -2*f/h, (h - 2*cy)/h, 0.0],
[0.0, 0.0, (-far - near) / (far - near), -2.0*far*near/(far-near)],
[0.0, 0.0, -1.0, 0.0]
])

So this is an opengl projection matrix so the result of multiplication is in clip space. Then I divide by w and I'm in NDC space.

Unfortunately so far what I get in NDC with my opengl matrix does not match what I get by multiplying with redner _cam_to_ndc and dividing by z.

I guess the problem lies with my projection matrix but to fix it I need to fully understand _cam_to_ndc

**Comment by francoisruty** [comment]
(btw I'm using opengl stuff to render vertex colors so if you do that in redner I won't need this whole stuff but still it's intellectually interesting to understand _cam_to_ndc :)

**Comment by BachiLi** [comment]
The `cam_to_ndc` matrix is indeed used for modelling the OpenCV-like camera models (i.e. the "intrinsic camera matrix" in vision terminology). The comments and naming were very confusing and I just fixed them (It doesn't transform to NDC anyways). Now the matrix is called `intrinsic_mat`. Sorry for the low code quality resulting from midnight coding.

The transformation of this matrix happens between the camera local space and the 3D-to-2D projection. That's why you still need to divide by z in the perspective camera model. In OpenGL, this transformation is merged into the projection matrix (notice the fov factors in your projection matrix). We additionally model the skew and the "principle point" of the camera. The multiplication with width and height (for transformation to raster space) is hardcoded in redner C++.

**Comment by francoisruty** [comment]
ok thanks, it's clearer now

**Comment by lith0613** [comment]
> ok thanks, it's clearer now

@francoisruty Hi, can you share how to transfer the camera opengl projection matrix into redner ?
