### ISSUE TITLE
CUDA Runtime Error: out of memory at /tmp/pip-req-build-0zs9vnan/buffer.h:55

### ISSUE THREAD

**Issue by Guptajakala** [BachiLi/redner#84]
Hi, when I try to run your tutorial exampes, and set 
`pyredner.set_use_gpu(True)`
I got the error "CUDA Runtime Error: out of memory at /tmp/pip-req-build-0zs9vnan/buffer.h:55"

But if I set 
`pyredner.set_use_gpu(False)`
That error disappears. Do you know what could be the problem?

System: Ubuntu16
GPU: K40c
Cuda: 10.1
pytorch: 1.2.0

**Comment by BachiLi** [comment]
Like the error message says your GPU runs out of memory. This is rare: how much memory do you have on your GPU and what is the resolution of the image you are rendering?

**Comment by Guptajakala** [comment]
@BachiLi 
Thanks for your timely reply!
I have updated my info above. The GPU has 12G RAM. I'm rendering the image HxW=480x640.

**Comment by BachiLi** [comment]
Looks related to https://github.com/BachiLi/redner/issues/77
It is difficult for me to track down this without a Tesla GPU around. This is most likely a bug (or bad documentation) in optix prime.

**Comment by BachiLi** [comment]
Just realized that I might be able to get a K40c. Will take a look tonight.

**Comment by Guptajakala** [comment]
@BachiLi 
After monitoring by nivida-smi, I found loading my OBJ file already takes ~9G memory.
Here is the OBJ file I'm using
https://drive.google.com/drive/folders/1GSmaPwlmyu26rohU7O67iQVotnAS1jwl?usp=sharing

`objects = pyredner.load_obj(obj_dir, return_objects=True)`

However, I haven't seen such a high memory usage using some opengl rendering engines.

**Comment by BachiLi** [comment]
OK, this is due to my hacky implementation of mipmapping. From the conclusion, the current workarounds are 1) add `torch.cuda.empty_cache()` after load_obj or 2) use a smaller texture.

My current mipmapping implementation builds an image "tower" instead of a pyramid: all the levels in the mipmap have the same size. The texture you use has the size of 4096x4096x3, which means that the mipmap has the size of 13x4096x4096x3 -- this takes around 2.4 GB. Since I build the mipmap inside PyTorch/TensorFlow, they would cache all the intermediate states of the mipmap building process as well, which leads to the 9GB consumption.

The ideal solution is to properly downsample the images when building the mipmap. This is not too difficult. I'll fix this soon.

**Comment by Guptajakala** [comment]
@BachiLi Really appreciate it!

**Comment by BachiLi** [comment]
@Guptajakala should be fixed in 0.3.0. Now the same object takes around 1GB for PyTorch to load it.

**Comment by Guptajakala** [comment]
Awesome, thank you so much!
