### ISSUE TITLE
Sample at Pixel Center

### ISSUE THREAD

**Issue by tetterl** [BachiLi/redner#98]
In PBRT there is a flag that allows to sample the ray from the center of the pixels: https://github.com/mmp/pbrt-v3/commit/6a9eec894534507db6fff6d052c7bbdb541421b1

This would be a great addition, e.g. for debugging, getting uv coordinates that are more equally spaced, ...

**Comment by BachiLi** [comment]
Added in https://github.com/BachiLi/redner/commit/884013e83c898535a62868b0ba9bd0d8f2f3aa56
Note that without antialiasing, rendering becomes non-differentiable w.r.t. vertex positions and camera (since there's no integral). The edge sampling would still act like there is an integral, so it's an approximation.

**Comment by BachiLi** [comment]
Fixed a bug at https://github.com/BachiLi/redner/commit/8d1a83740f4703540bd65c7d857cd8c9cd89d46a

**Comment by tetterl** [comment]
Thanks! (FYI: version bump is missing)
